name: Lint

on:
  pull_request:
    types: [opened, synchronize, edited, reopened]
    branches:
      - main
      - develop
      - task/**
  push:
    branches:
      - main

jobs:
  eslint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18.20.3" # Sử dụng phiên bản Node.js phù hợp với dự án của bạn

      - name: Cache node modules
        uses: actions/cache@v3
        env:
          cache-name: cache-node-modules
        with:
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: Install Dependencies
        run: yarn install

      - name: Run ESLint
        run: yarn lint

      - name: Run Prettier Check
        run: yarn prettier --check ./app

      - name: Run TypeScript Check
        run: yarn tsc --noEmit

      - name: Run Tests
        run: yarn test

      - name: Run ESLint on changed files
        id: eslint
        run: npx eslint --no-error-on-unmatched-pattern $(git diff --diff-filter=d --name-only origin/${{ github.event.pull_request.base.ref }}... -- . ":(exclude)**/test-coverage*" | grep -E '\.(js|jsx)$' | xargs || echo "")

      - name: Create comment if there are errors
        if: failure()
        uses: actions/github-script@v6
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: 'Lint error!'
            })