name: Test Badge Creation

on:
  push:
    branches:
      - main

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Create a simple badge
        uses: schneegans/dynamic-badges-action@v1.7.0
        with:
          auth: ${{ secrets.GIST_SECRET }}
          gistID: cd5918bdaba99e0df6b4d2305b605032
          filename: pet-pamper-client.json
          label: Coverage
          message: 80%
          color: brightgreen
          namedLogo: javascript
