name: Test Badge Creation

on:
  push:
    branches:
      - main

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Create a simple badge
        uses: schneegans/dynamic-badges-action@v1.7.0
        with:
          auth: ${{ secrets.GIST_SECRET }}
          gistID: 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
          filename: pet-pamper-client.json
          label: Coverage
          message: 80%
          color: brightgreen
          namedLogo: javascript
